import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" data-theme="dracula">
            <head>
                <script
                    defer
                    src="https://kit.fontawesome.com/42adea93eb.js"
                    crossOrigin="anonymous"
                ></script>
            </head>
            <body className={inter.className}>{children}</body>
        </html>
    )
}
